language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: YQlfLeLzg9S1gdstCGjFAccTkBiT5UF+WCT96p865cUfR5jduWWkc5aAcltvPAWeJnI4cRWieVI22x7Bz5CvpX3av4QRFsJG+WtH+dVKY61KaCoUy9q2RHJ48YwNdWjAr4RKdLkoxV8QIMRRjv7ndwYPaiisTL7uY4Br9oeqxIs0CdLoJHG0Bq8ig03w10KP5iX/0EdPJKttrqS4DWMN3jvqT2kszDS1LiWbIPdINr9jklv4EMzShJ7y2MAGI3+O1+0w5XxInUFYynDz2YZN3MGCWpC3RfSNlw9cBbHjjlXJ6G34TH2F5CgyGClD810+MSV5ZFfF9POXHNqyYbsQS7wdBDin/WynF5wH0tBfH48qhzGGcIXNgdOApUVQghg9KrN49ViIpHA2Hr+2FORWdO7MavKm9sECaZg3M59nNNNuZroeCAppxHOXSDhmULWil3Ul4czgOVTQIh7aWu13nfI1QTM669bEQniMfke+pJAxWalxYECthFVWDWS7mDoLVLCrKXHFmTmIJ2jkqdUqvp6mgSFEZRNvl5j9Wl4gPskpsBtbz+V2FLX/2iGnwG59J/dChpmsqcyMLvYmPI3w3lw5Ew5UFR1MLgBZcUrNlu58VnaQIc6/Id23DZGKT5oafHyoTi4OZdNFJ0of3CpmDzWlvuk3K+tFSg16OIwpsq4=
  app: stark-spire-27149
  on:
    repo: Bjthomas11/where-to-places
